urls.py
from django.conf.urls.defaults import patterns, include, handler404, handler500
from django.conf.urls.defaults import url
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^/?$', 'views.index', name='index'),
    
    url(r'^tails/$', 'tail.views.tails', name='tail_tails'),
    url(r'^tail/create/$', 'tail.views.create', name='tail_create'),
    url(r'^tail/data/(?P<tail_id>.+)/$', 'tail.views.data', name='tail_data'),
    url(r'^tail/(?P<tail_id>.+)/$', 'tail.views.tail', name='tail_tail'),
    
    url(r'^login/$', 'accounts.views.login', name='login'),
    url(r'^logout/$', 'accounts.views.logout', name='logout'),
    
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'^media/(?P<path>.*)$', 'serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

tail/models.py
import datetime
import os

from django.db import models
from django.core.urlresolvers import reverse

from django_ext.crypto import box
from django_ext.utils import cached_property

from django.contrib.auth.models import User

class ServerTail(models.Model):
    hostname = models.TextField()
    port = models.IntegerField(default=22)
    username = models.TextField()
    password = models.TextField(blank=True, default='')
    path = models.TextField()
    user = models.ForeignKey(User, null=True, blank=True)
    date_created = models.DateTimeField(default=datetime.datetime.now)
    
    class Meta(object):
        ordering = ['-date_created']
    
    @cached_property
    def boxed_id(self):
        return box(self.id)
    
    @cached_property
    def filename(self):
        print os.path.split(self.path.split()[0])[1]
        return os.path.split(self.path.split()[0])[1]
    
    def __unicode__(self):
        return self.hostname
    
    def get_absolute_url(self):
        return reverse('tail_tail', args=[self.boxed_id])


class FrontPage(models.Model):
    server_tail = models.ForeignKey(ServerTail)
    date = models.DateTimeField(default=datetime.datetime.now)
    
    def __unicode__(self):
        return u'%s was featured on %s' % (self.server_tail, self.date)

tail/forms.py
from django import forms

from tail.models import ServerTail

class ServerTailForm(forms.Form):
    hostname = forms.CharField(max_length=50)
    port = forms.IntegerField(initial=22)
    username = forms.CharField(max_length=50)
    password = forms.CharField(
        widget=forms.PasswordInput(render_value=False),
        required=False,
        label='Password (optional)',
    )
    path = forms.CharField(max_length=255, label='Path to log file')
    
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        if self.user:
            if not self.user.is_authenticated():
                self.user = None
        super(ServerTailForm, self).__init__(*args, **kwargs)
    
    def save(self):
        st, created = ServerTail.objects.get_or_create(
            hostname=self.cleaned_data['hostname'],
            port=self.cleaned_data['port'],
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password'],
            path=self.cleaned_data['path'],
            user=self.user,
        )
        return st

tail/views.py
import operator
import os
import uuid

from collections import defaultdict

from django.shortcuts import render_to_response, get_object_or_404
from django.http import Http404, HttpResponseRedirect, HttpResponseForbidden
from django.http import HttpResponse
from django.template import RequestContext

from django_ext.http import JSONResponse
from django_ext.crypto import unbox

from django.contrib.auth.decorators import login_required

import eventlet
from eventlet import event

import paramiko

from tail.models import ServerTail
from tail.forms import ServerTailForm
from tail.utils import get_public_key

def tail(request, tail_id=None):
    try:
        tail_id = unbox(tail_id.encode('utf-8'))
    except (ValueError, TypeError):
        raise Http404
    server_tail = get_object_or_404(ServerTail, id=tail_id)
    context = {
        'server_tail': server_tail,
        'public_key': get_public_key(),
    }
    return render_to_response('tail/tail.html', context,
        context_instance=RequestContext(request))

@login_required
def tails(request):
    if request.method == 'POST':
        if 'tail_id' not in request.POST:
            raise Http404
        try:
            tail_id = int(request.POST['tail_id'])
        except (ValueError, TypeError):
            raise Http404
        server_tail = get_object_or_404(ServerTail, id=tail_id)
        if server_tail.user != request.user:
            return HttpResponseForbidden('Not allowed')
        server_tail.delete()
        return HttpResponseRedirect(request.path)
    
    return render_to_response('tail/tails.html', {},
        context_instance=RequestContext(request))

def create(request):
    form = ServerTailForm(request.POST or None, user=request.user)
    if form.is_valid():
        st = form.save()
        if 'iframe' in request.REQUEST:
            tmpl = '<script type="text/javascript">parent.location="%s"</script>'
            return HttpResponse(tmpl % (st.get_absolute_url(),))
        else:
            return HttpResponseRedirect(st.get_absolute_url())
    context = {
        'form': form,
    }
    return render_to_response('tail/create.html', context,
        context_instance=RequestContext(request))

class DataCollectionView(object):
    
    def __init__(self, idle_time=5*60, buffer_limit=100):
        self.data = defaultdict(lambda: [])
        self.getters = {}
        self.cancelers = {}
        self.events = defaultdict(lambda: [])
        self.idle_time = idle_time
        self.buffer_limit = buffer_limit
    
    def _get_latest_lines(self, tail_id, cursor):
        # There's gotta be a more elegant way to write this
        if not cursor:
            return self.data[tail_id]
        lines = []
        seen_cursor = False
        for line in self.data[tail_id]:
            if seen_cursor:
                lines.append(line)
            elif line['id'] == cursor:
                seen_cursor = True
        return lines
    
    def view(self, request, tail_id=None):
        try:
            tail_id = unbox(tail_id.encode('utf-8'))
        except (ValueError, TypeError):
            raise Http404
        
        getter = self.getters.get(tail_id)
        if getter:
            # Cancel the canceler and start a new one for later
            #if tail_id in self.cancelers:
            #    self.cancelers[tail_id].cancel()
            #self.cancelers[tail_id] = eventlet.spawn_after(self.idle_time,
            #    self.stop_get_data, tail_id)
            pass
        else:
            server_tail = get_object_or_404(ServerTail, id=tail_id)
            self.getters[tail_id] = eventlet.spawn(self.get_data,
                server_tail)
            #self.cancelers[tail_id] = eventlet.spawn_after(self.idle_time,
            #    self.stop_get_data, tail_id)
        
        cursor = request.GET.get('cursor')
        
        lines = self._get_latest_lines(tail_id, cursor)
        
        if not lines:
            data_event = event.Event()
            self.events[tail_id].append(data_event)
            resp = data_event.wait()
            if resp['error']:
                return JSONResponse({'error': True},
                    request.GET.get('callback'))
            lines = self._get_latest_lines(tail_id, cursor)
    
        # Their cursor could just have been way too far back
        if not lines:
            lines = self.data[tail_id]
        
        new_cursor = lines[-1]['id'] if lines else None
        
        lines = map(operator.itemgetter('line'), lines)
        
        return JSONResponse({
            'cursor': new_cursor,
            'lines': lines,
        }, request.GET.get('callback'))
    
    def _get_data(self, server_tail):
        print 'Starting data getter for ServerTail %s' % (server_tail.id,)
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        kwargs = {'timeout': 10}
        if server_tail.username:
            kwargs['username'] = server_tail.username
        if server_tail.password:
            kwargs['password'] = server_tail.password
        rsa_key = '/home/servertail/.ssh/id_rsa'
        if os.path.exists(rsa_key):
            kwargs['key_filename'] = rsa_key
        client.connect(server_tail.hostname, server_tail.port, **kwargs)
        
        command = 'uname -a'
        stdin, stdout, stderr = client.exec_command(command)
        if 'Darwin' in stdout.read():
            command = 'tail -n%s -F %s' % (self.buffer_limit, server_tail.path)
        else:
            command = 'tail -q -s0.08 -n%s -F %s 2>&1' % (self.buffer_limit,
                server_tail.path)
        
        stdin, stdout, stderr = client.exec_command(command)
        
        for line in stdout:
            line_id = str(uuid.uuid1())
            self.data[server_tail.id].append({
                'id': line_id,
                'line': line.rstrip(),
            })
            truncated = self.data[server_tail.id][-self.buffer_limit:]
            self.data[server_tail.id] = truncated
            events = self.events.pop(server_tail.id, [])
            for event in events:
                event.send({'error': False, 'id': line_id})
    
    def get_data(self, server_tail):
        try:
            return self._get_data(server_tail)
        except (KeyboardInterrupt, SystemExit):
            raise
        except:
            events = self.events.pop(server_tail.id, [])
            for event in events:
                event.send({'error': True})
    
    def stop_get_data(self, tail_id):
        print 'Canceling data getter for ServerTail %s' % (tail_id,)
        getter = self.getters.pop(tail_id, None)
        if getter:
            getter.kill()
        self.data[tail_id] = []
        self.cancelers.pop(tail_id, None)
        self.events.pop(tail_id, [])

data = DataCollectionView().view

templates/tail/create.html
{% extends "iframe_base.html" %}

{% block title %}Create a new Tail &ndash; {{ block.super }}{% endblock %}

{% block content %}
    <h1>Create New Tail</h1>
    <form method="POST" id="new-tail">
        {% csrf_token %}
        <ul>
            {{ form.as_ul }}
        </ul>
        <input type="hidden" name="iframe" value="true" />
        <input type="submit" value="Create" />
    </form>
{% endblock %}

templates/tail/tail.html
{% extends "base.html" %}

{% block title %}{{ server_tail.filename }} &ndash; {{ server_tail.hostname }} &ndash; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
  <li>{{ server_tail.path }}</li>
{% endblock %}

{% block content %}  
  <article id="log">
    <section class="heading">
      <header>
        <h1>{{ server_tail.filename }}</h1>
      </header>
      <aside class="actions">
        <a href="#" id="start-tail"><span>Start</span></a>
        <a href="#" id="stop-tail" style="display: none"><span>Stop</span></a>
        <a href="{% url tail_create %}" id="new-tail" class="tail-create"><span>New Tail</span></a>
      </aside>
    </section>
    
    <section class="content">
      <section id="waiting-help">
        <h2>We&rsquo;re Trying to Connect Now...</h2>
        <p>Is this taking a long time?</p>
        <ul>
            {% if server_tail.password %}
                <li>
                    Make sure the password you entered is correct for the user
                    <strong>{{ server_tail.username }}@{{ server_tail.hostname }}</strong>.
                </li>
            {% else %}
                <li>
                    If you haven't already, Make sure our public key is added to your server&rsquo;s
                    <em>authorized_keys</em> file.
                    To add our key to your file, you can run this command on the server:
                    <textarea>mkdir -p ~/.ssh &amp;&amp; touch ~/.ssh/authorized_keys &amp;&amp; echo &quot;{{ public_key }}&quot; &gt;&gt; ~/.ssh/authorized_keys</textarea>
                </li>
            {% endif %}
            <li>
                Also, make sure that the hostname <strong>{{ server_tail.hostname }}</strong>
                is accessible on port <strong>{{ server_tail.port }}</strong>.
            </li>
        </ul>
      </section>
      <table id="lines"></table>
    </section>
  </article>
  
{% endblock %}

{% block extra_body %}
    <script type="text/javascript" charset="utf-8">
        Tail.setup('{% url tail_data server_tail.boxed_id %}', '#lines');
        $(window).load(function() {
            setTimeout(Tail.start, 50);
        });
    </script>
{% endblock %}

templates/tail/tails.html
{% extends "base.html" %}

{% block title %}My Tails &ndash; {{ block.super }}{% endblock %}

{% block content %}        
    <article id="tails" class="group">
      <section class="heading">
        <header>
          <h1>My Tails</h1>
        </header>
        <aside class="actions group">
          <a href="{% url tail_create %}" id="new-tail" class="tail-create"><span>New Tail</span></a>
        </aside>
      </section>

      <section class="content group">
            {% for tail in user.servertail_set.all %}
              <ul class="group">
                <li><a href="{{ tail.get_absolute_url }}">{{ tail.hostname }} &ndash; {{ tail.path }}</a>
                    <form method="POST" class="delete">
                        {% csrf_token %}
                        <input type="hidden" name="tail_id" value="{{ tail.id }}" />
                        <input type="submit" value="X" />
                    </form>
                </li>
              </ul>
            {% empty %}
                <div id="empty" class="group"><h2>Sadness...</h2>
                    <p>You don&rsquo;t seem to have any tails yet, why not
                    <a href="{% url tail_create %}" class="tail-create">create one now</a>?</p>
                </div>
            {% endfor %}
      </section>
    </article>
{% endblock %}